security:
  oauth2:
    client:
      # From OIDC app
      # From Authorization Server's metadata
      accessTokenUri: https://prosper.okta.com/oauth2/default/v1/token
      userAuthorizationUri: https://prosper.okta.com/oauth2/default/v1/authorize
#      pre-established-redirect-uri: https://nevexcomputing.com/voting
    resource:
      # from your Auth Server's metadata
      userInfoUri: https://prosper.okta.com/oauth2/default/v1/userinfo

