voting-with-okta:
  saml-hostname: localhost:${server.port}
  keystore-resource: saml/keystore.jks
  admin-key: boston
  protocol: https
  add-test-data: false

security:
  basic:
    enabled: false
  filter-order: 5
  saml2:
#    metadata-url: https://dev-309873.oktapreview.com/app/exkcujynn6dhbolHb0h7/sso/saml/metadata
    metadata-url: https://dev-309873.oktapreview.com/app/exkcurhhvaLJwRbrb0h7/sso/saml/metadata # local server
#    metadata-url: https://prosper.okta.com/app/prospermarketplaceinc_uxhackathonvoting_2/exk1d5me3qf31Fb6t1d8/sso/saml
#    metadata-url: https://prosper.okta.com/app/exk1d5me3qf31Fb6t1d8/sso/saml/metadata

server:
  context-path: /voting
  port: 56910
  ssl:
    enabled: true
    key-alias: voting-with-okta-saml
    key-store: src/main/resources/${voting-with-okta.keystore-resource}

spring:
#  jackson:
#    serialization:
#      serialization:
#            INDENT_OUTPUT: true --> causes problems with hsql
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    mode: HTML5
    suffix: .html
  datasource:
    url: jdbc:hsqldb:file:database/voting
    username: sa
  jpa:
    show-sql: false
    hibernate.ddl-auto: create # dump the data for now on each start


